'use strict';
window.PORTFOLIO_PROJECTS = [
  {id:'fps',name:'FPS 帧律',repo:'fps-tune',role:'原创项目',category:'windows',tags:'C# / WPF / .NET',description:'系统层帧率调校台。先检测、再解释，用 A/B 实测判断优化是否值得保留。',image:'fps-tune.png',imageAlt:'FPS 帧律的实际概览界面，展示检测状态与系统优化项。',subtitle:'优化有没有用，让这台电脑的实测结果回答。',problem:'Windows 优化选项散落在不同位置，改了哪些东西、有没有收益、怎么恢复，很难说清楚。',approach:'把 36 项系统层优化汇入一份可审阅的目录。GUI 与 CLI 共用引擎，写入前备份原值；A/B 实验用基线与候选组对比，满足规则才保留。',result:'从检测、解释、确认，到执行、还原和导出报告，形成完整工作流。AI Agent 也能通过无头 CLI 使用同一套能力。',boundary:'实际收益取决于硬件、驱动与游戏条件，不承诺固定帧率提升。真实帧率采样需要 PresentMon。',links:[['项目文档','https://github.com/jidekaixin2dian/fps-tune#readme'],['发行版本','https://github.com/jidekaixin2dian/fps-tune/releases'],['优化目录','https://github.com/jidekaixin2dian/fps-tune/blob/main/catalog/catalog.json']]},
  {id:'desk',name:'PiWeb Desk',repo:'piweb-desk',role:'原创桌面外壳',category:'windows',tags:'Electron / Node.js',description:'给 AI 编码工具一个桌面入口。任务通知、费用雷达和全局热键，让长任务更容易照看。',image:'piweb-desk.png',imageAlt:'PiWeb Desk 的真实桌面界面，显示 AI 会话与项目导航。',subtitle:'任务在跑，人不用一直盯着窗口。',problem:'浏览器里的 AI 编码会话容易被窗口淹没。任务完成了没有、今天花了多少、怎样快速回到项目，都需要更直接的入口。',approach:'围绕 pi-web 构建 Windows 桌面外壳。监听会话结束状态、汇总 token 成本，提供系统托盘、全局热键和文件夹右键入口。',result:'自包含运行时让目标机器无需另装 Node.js。任务完成时提供通知，费用汇总在托盘里可见，Ctrl+Alt+P 可以呼出或隐藏窗口。',boundary:'这是基于 agegr/pi-web 的第三方桌面外壳；AI 编码内核与 Web UI 来自上游项目。',links:[['项目文档','https://github.com/jidekaixin2dian/piweb-desk#readme'],['发行版本','https://github.com/jidekaixin2dian/piweb-desk/releases'],['上游 pi-web','https://github.com/agegr/pi-web']]},
  {id:'handoff',name:'handoff',repo:'handoff',role:'原创 Skill',category:'agent',tags:'Agent Skills / Markdown',description:'换个对话，项目接着做。先核实工作区，再把当前状态、下一步和证据入口交清楚。',visual:'handoff',subtitle:'上下文会换，项目的线索要留下。',problem:'长任务换到新对话，往往要重讲背景。旧文档中的版本、已完成事项与计划又可能已经过期。',approach:'先核实真实工作区，再把当前状态、下一步、关键约束和证据入口整理到轻量交接入口。原始证据保留，细节按需读取。',result:'不需要额外服务，通过纯指令 skill 让下一位 Agent 或同事更快找到可靠起点。',boundary:'检查通过与人工接受分别记录。项目公开检查记录中尚未包含跨模型评测或 token 节省测量。',links:[['技能源码','https://github.com/jidekaixin2dian/handoff/blob/main/skills/handoff/SKILL.md'],['交接示例','https://github.com/jidekaixin2dian/handoff/blob/main/docs/example.md'],['检查记录','https://github.com/jidekaixin2dian/handoff/blob/main/docs/validation.md']]},
  {id:'storage',name:'storage-analyzer',repo:'storage-analyzer',role:'Windows 维护分支',category:'windows',tags:'Python / PowerShell / HTML',description:'把磁盘占用变成能看懂、能判断的报告。针对 Windows 的编码、链接和回收站行为做完整适配。',visual:'storage',subtitle:'空间从哪里来，清理之前先弄清楚。',problem:'磁盘扫描在 Windows 上会遇到编码、junction 重复计数和报告服务状态等问题；占得多，也不等于可以直接删除。',approach:'基于 Khazix 的原始 skill，针对 Windows 重做扫描与报告链路：UTF-8 输出、跳过兼容链接、服务状态提示，以及受边界约束的回收站删除。',result:'只读扫描与三级分诊连接到交互式报告，让占用量、依据和处置路径一起可见。',boundary:'原始设计、分诊体系与安全模型来自数字生命卡兹克（Khazix）。我的工作是 Windows 特化与后续维护。',links:[['维护说明','https://github.com/jidekaixin2dian/storage-analyzer#readme'],['实现源码','https://github.com/jidekaixin2dian/storage-analyzer/tree/main/scripts'],['原始项目','https://github.com/KKKKhazix/khazix-skills']]},
  {id:'codex',name:'DSH Codex UI',repo:'dsh-codex-ui',role:'开源贡献',category:'interface',tags:'UI / Theme tokens',compact:true,description:'在社区界面插件中修复发送按钮的语义色。主题切换后，关键操作仍然清楚可见。',subtitle:'一个按钮，也值得把它修对。',problem:'皮肤改写颜色别名后，发送按钮可能出现黑色背景、图标看不清的问题。',approach:'把发送按钮颜色改为按钮语义色，减少对容易被皮肤覆盖的通用别名令牌的依赖。',result:'修复提交已通过上游 PR #33 合入。项目的侧栏、搜索与会话导航由 MichengAI 社区维护。',boundary:'我的参与是具体修复贡献。DSH Codex UI 的整体开发与维护属于上游社区。',links:[['已合入的 PR #33','https://github.com/MichengAI/dsh-codex-ui/pull/33'],['社区上游','https://github.com/MichengAI/dsh-codex-ui']]},
  {id:'pi',name:'pi-web · 模型发现',repo:'pi-web',role:'开源贡献',category:'agent',tags:'Provider catalog / API',compact:true,description:'让模型发现从 provider 目录解析端点。把配置、协议与实际请求接到一起。',subtitle:'减少配置里的猜测，让请求走对入口。',problem:'模型发现需要识别不同 provider 的 API 协议与端点，单一假设容易让某些 provider 请求走错路径。',approach:'从 pi 的 provider catalog 解析模型发现端点，使目录里的 provider 元信息参与请求构建。',result:'功能提交已通过上游 PR #1006 合入，改善模型配置流程中的发现行为。',boundary:'pi-web 是 agegr 维护的 Web UI；我的参与是模型发现功能贡献。',links:[['已合入的 PR #1006','https://github.com/agegr/pi-web/pull/1006'],['社区上游','https://github.com/agegr/pi-web']]},
  {id:'wallpaper',name:'DSH Wallpaper Engine',repo:'dsh-wallpaper-engine',role:'Fork / 改进提案',category:'interface',tags:'Wallpaper / Typography',compact:true,description:'围绕壁纸界面与字体体验进行探索，提出让全界面文字跟随宿主字体选择的修复。',subtitle:'好用的工作台，也可以有自己的气质。',problem:'壁纸插件里的字族设置需要与宿主字体选择保持一致，避免界面局部使用不同字体。',approach:'在 Fork 中提出字体令牌修复，让插件字族读取宿主源头令牌，并提交到上游讨论。',result:'修复提案可在上游 PR #100 查看。当前为已关闭、未合入状态。',boundary:'壁纸插件由 elysia395 与社区维护。这个条目是改进提案，尚未合入上游。',links:[['修复提案 PR #100','https://github.com/elysia395/dsh-wallpaper-engine/pull/100'],['研究分支','https://github.com/jidekaixin2dian/dsh-wallpaper-engine'],['社区上游','https://github.com/elysia395/dsh-wallpaper-engine']]},
  {id:'sidebar',name:'DSH Better Sidebar',repo:'DSH-better-sidebar',role:'Fork / 架构研究',category:'interface',tags:'Plugins / Workbench',compact:true,description:'探索把文件预览、终端和 Git 放进同一工作台的插件架构，研究 Agent 与界面的连接方式。',subtitle:'把散落的工具，放回同一个工作现场。',problem:'Agent 工作流经常需要在文件、终端、版本控制和会话之间来回切换。',approach:'跟进开放侧边栏底座与插件注册机制，研究文件预览、终端和工作台如何在同一界面协作。',result:'保留公开 Fork 作为研究入口，可继续查看框架与上游插件接入文档。',boundary:'工作台框架由 omdsh-dev 社区维护；我的参与以跟进与架构研究为主。',links:[['研究分支','https://github.com/jidekaixin2dian/DSH-better-sidebar'],['社区上游','https://github.com/omdsh-dev/DSH-better-sidebar'],['插件接入文档','https://github.com/omdsh-dev/DSH-better-sidebar/blob/main/docs/external-plugin-guide.md']]}
];
