'use strict';
const PROJECTS=window.PORTFOLIO_PROJECTS;
const $=(selector)=>document.querySelector(selector);
function renderProjects(filter='all'){
  const items=PROJECTS.filter(p=>filter==='all'||p.category===filter);
  $('#result-count').textContent=`${items.length} 件作品`;
  $('#projects').innerHTML=items.map((p,i)=>`<article class="project-card ${p.compact?'compact':''}" data-project="${p.id}" style="animation-delay:${Math.min(i,4)*35}ms">${p.image?`<div class="project-visual"><img src="./${p.image}" alt="${p.imageAlt}" loading="lazy" width="1280" height="800"></div>`:p.visual==='handoff'?'<div class="project-visual handoff-visual" aria-hidden="true"><span class="handoff-statement">换个对话，<br>项目接着做。</span><div class="handoff-flow"><span>状态</span><i></i><span>证据</span><i></i><span>下一步</span></div></div>':p.visual==='storage'?'<div class="project-visual storage-visual" aria-hidden="true"><span class="storage-statement">先看清楚。<br><strong>再腾空间。</strong></span><div class="storage-method"><span>扫描</span><span>判断</span><span>报告</span><span>处置</span></div></div>':''}<div class="project-body"><div class="project-meta"><span class="project-role">${p.role}</span><span>${p.tags}</span></div><h3>${p.name}</h3><p>${p.description}</p><div class="project-actions"><button data-open="${p.id}" aria-label="查看 ${p.name} 项目详情">项目详情</button><a href="https://github.com/jidekaixin2dian/${p.repo}" target="_blank" rel="noopener noreferrer" aria-label="在 GitHub 查看 ${p.name}">SOURCE CODE</a></div></div></article>`).join('');
}
renderProjects();
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});renderProjects(button.dataset.filter);}));
const ABILITIES=[
  {id:'engineering',title:'把工具做完整',label:'软件工程',description:'从 Windows 原生界面到桌面外壳，把检测、配置、执行和恢复接成一条可用的流程。也给自动化保留明确的 CLI 入口。',stack:['C# · WPF · .NET','Electron · Node.js','Python · PowerShell'],evidence:[['fps','帧律：GUI 与 CLI 共用引擎'],['desk','PiWeb Desk：自包含桌面运行时']]},
  {id:'workflow',title:'让长任务接得下去',label:'AI 工作流',description:'整理状态与证据，把上下文交接变成可重复的方法。关注工具入口、配置契约，以及不同 Agent 之间的工作连续性。',stack:['Agent Skills','状态核实与交接','Provider API'],evidence:[['handoff','handoff：当前状态与证据入口'],['pi','pi-web：provider 目录与模型发现']]},
  {id:'experience',title:'照顾真实使用的细节',label:'产品与界面',description:'完成通知、热键、主题和字体这些细节，让长时间使用的工具更顺手。遇到体验问题，追到令牌、状态与实际请求。',stack:['桌面交互','主题语义色','界面兼容性'],evidence:[['desk','PiWeb Desk：任务通知与全局热键'],['codex','DSH Codex UI：主题按钮修复']]},
  {id:'validation',title:'让结论有依据',label:'验证与排错',description:'改动前看状态，执行后看结果。用实测、日志、目录约束和可恢复方案减少猜测，让下一次接手也知道结论从哪里来。',stack:['A/B 实测','可逆变更','证据与边界'],evidence:[['fps','帧律：有实测收益才保留'],['storage','storage-analyzer：扫描与清理边界']]}
];
$('#extended-content').innerHTML=`<section class="abilities shell" id="abilities" aria-labelledby="abilities-title"><div class="section-heading"><h2 id="abilities-title">我的能力，<br>在作品里。</h2><p class="section-description">选一个方向，看看对应的工作。</p></div><div class="ability-layout"><div class="ability-tabs" role="tablist" aria-label="能力方向" aria-orientation="vertical">${ABILITIES.map((a,i)=>`<button id="tab-${a.id}" role="tab" aria-selected="${i===0}" aria-controls="ability-panel" tabindex="${i===0?0:-1}" data-ability="${a.id}"><span class="ability-number">0${i+1}</span>${a.label}<span class="tab-indicator" aria-hidden="true">+</span></button>`).join('')}</div><div id="ability-panel" role="tabpanel" tabindex="0"></div></div></section><section class="about shell" id="about" aria-labelledby="about-title"><div class="about-signature"><span class="oversize-mark" aria-hidden="true">jk.</span><span class="mono">jidekaixin2dian</span></div><div class="about-copy"><h2 id="about-title">记得开心一点。<br>也记得把事情做完。</h2><p>我喜欢折腾电脑，也喜欢把折腾过的路铺平。帧率调校、AI 编码、工作流交接，这些项目都从自己遇到的问题开始。</p><p>我关心一个工具能不能真的用起来，出了问题能不能查清楚，换个人接手能不能继续。好奇心负责开始，验证和耐心负责走到最后。</p><div class="principles"><span>从实际问题出发</span><span>把复杂留给实现</span><span>让结果经得起检查</span></div><div class="contact-actions"><a class="button primary" href="https://github.com/jidekaixin2dian" target="_blank" rel="noopener noreferrer">到 GitHub 认识我</a><button id="copy-profile" class="button secondary">复制 GitHub 地址</button></div></div></section>`;
function setAbility(id){const a=ABILITIES.find(a=>a.id===id);if(!a)return;document.querySelectorAll('[data-ability]').forEach(b=>{const selected=b.dataset.ability===id;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;});$('#ability-panel').setAttribute('aria-labelledby',`tab-${id}`);$('#ability-panel').innerHTML=`<h3>${a.title}</h3><p>${a.description}</p><div class="stack-tags">${a.stack.map(t=>`<span>${t}</span>`).join('')}</div><div class="ability-evidence"><h4>在这些作品中体现</h4>${a.evidence.map(([p,label])=>`<button data-open="${p}">${label}<span aria-hidden="true">+</span></button>`).join('')}</div>`;}
setAbility(ABILITIES[0].id);
document.querySelectorAll('[data-ability]').forEach((b,index)=>{b.addEventListener('click',()=>setAbility(b.dataset.ability));b.addEventListener('keydown',e=>{let next=index;if(e.key==='ArrowDown'||e.key==='ArrowRight')next=(index+1)%ABILITIES.length;else if(e.key==='ArrowUp'||e.key==='ArrowLeft')next=(index-1+ABILITIES.length)%ABILITIES.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=ABILITIES.length-1;else return;e.preventDefault();setAbility(ABILITIES[next].id);document.querySelector(`[data-ability="${ABILITIES[next].id}"]`).focus();});});
let previouslyFocused=null;
function openProject(id){const p=PROJECTS.find(p=>p.id===id);if(!p)return;previouslyFocused=document.activeElement;$('#dialog-content').innerHTML=`<div class="dialog-meta"><span>${p.role}</span><span>${p.tags}</span></div><h2 id="dialog-title">${p.name}</h2><p class="dialog-subtitle">${p.subtitle}</p>${p.image?`<img class="dialog-image" src="./${p.image}" alt="${p.imageAlt}" width="1280" height="800">`:''}<div class="project-notes"><section><h3>遇到的问题</h3><p>${p.problem}</p></section><section><h3>怎么解决</h3><p>${p.approach}</p></section><section><h3>做到了什么</h3><p>${p.result}</p></section></div><p class="project-boundary">${p.boundary}</p><div class="source-links">${p.links.map(([label,url])=>`<a class="button" href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>`).join('')}</div>`;const dialog=$('#project-dialog');if(!dialog.open)dialog.showModal();document.body.classList.add('dialog-open');dialog.scrollTop=0;$('#dialog-close').focus();}
document.addEventListener('click',e=>{const opener=e.target.closest('[data-open]');if(opener)openProject(opener.dataset.open);});
$('#dialog-close').addEventListener('click',()=>$('#project-dialog').close());
$('#project-dialog').addEventListener('click',e=>{if(e.target!==e.currentTarget)return;const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.currentTarget.close();});
$('#project-dialog').addEventListener('close',()=>{document.body.classList.remove('dialog-open');if(previouslyFocused?.isConnected)previouslyFocused.focus({preventScroll:true});});
let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
$('#copy-profile').addEventListener('click',async()=>{try{if(!navigator.clipboard?.writeText)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText('https://github.com/jidekaixin2dian');toast('GitHub 地址已复制。');}catch{toast('复制不可用，请直接使用旁边的 GitHub 链接。');}});
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target);}},{threshold:.12});document.querySelectorAll('.abilities,.about').forEach(s=>{s.classList.add('reveal');observer.observe(s);});}
